# Generated by Django 3.2.4 on 2021-08-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('lic', models.IntegerField(primary_key=True, serialize=False)),
                ('shop', models.CharField(max_length=100)),
                ('dealer', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin', models.IntegerField()),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'dealer',
            },
        ),
    ]
