# Generated by Django 3.2.4 on 2021-09-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('unit', models.IntegerField()),
                ('quality', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
