# Generated by Django 3.2.4 on 2021-09-13 16:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin', models.IntegerField()),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='General_Item_Order',
            fields=[
                ('order_no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('id', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('price', models.IntegerField()),
                ('order_date', models.DateField(default=datetime.date.today)),
                ('qty', models.IntegerField()),
                ('status', models.CharField(default='No', max_length=10)),
                ('deal_id', models.IntegerField(default=0)),
                ('bill_amount', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'general_item_order',
            },
        ),
        migrations.CreateModel(
            name='Medicinal_Item_Order',
            fields=[
                ('order_no', models.IntegerField(primary_key=True, serialize=False)),
                ('order_date', models.DateField(default=datetime.date.today)),
                ('med_name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('scale', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('lic', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('allot_status', models.CharField(blank=True, max_length=100, null=True)),
                ('deal_id', models.IntegerField(blank=True, null=True)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'db_table': 'medicinal_item_order',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feed_id', models.IntegerField(primary_key=True, serialize=False)),
                ('feed', models.CharField(max_length=100)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('lic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.dealer')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='Complaint_Registration',
            fields=[
                ('comp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('complaint', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('lic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.dealer')),
            ],
            options={
                'db_table': 'complaint_registration',
            },
        ),
    ]
